/** Supabase table names for marketplace module persistence. */
export const MarketplaceSnapshotTables = Object.freeze({
  carts: "marketplace_cart_snapshots",
  favorites: "marketplace_favorites_snapshots",
  reviews: "marketplace_review_snapshots",
  warehouseTasks: "marketplace_warehouse_task_snapshots",
  couriers: "marketplace_courier_snapshots",
  courierAssignments: "marketplace_courier_assignment_snapshots",
  deliveryRoutes: "marketplace_delivery_route_snapshots",
  customers: "marketplace_customer_snapshots",
  customerAddresses: "marketplace_customer_address_snapshots",
  sellers: "marketplace_seller_capability_snapshots",
  catalogs: "marketplace_catalog_capability_snapshots",
  categories: "marketplace_category_capability_snapshots",
  inventoryItems: "marketplace_inventory_item_snapshots",
  inventoryReservations: "marketplace_inventory_reservation_snapshots",
  inventoryMovements: "marketplace_inventory_movement_snapshots",
  prices: "marketplace_price_capability_snapshots",
  priceRules: "marketplace_price_rule_capability_snapshots",
  discounts: "marketplace_discount_capability_snapshots",
  promotions: "marketplace_promotion_capability_snapshots",
  listings: "marketplace_listing_capability_snapshots",
  moderationRequests: "marketplace_moderation_capability_snapshots",
  supportTickets: "marketplace_support_ticket_capability_snapshots",
  supportComplaints: "marketplace_support_complaint_capability_snapshots",
  supportSuggestions: "marketplace_support_suggestion_capability_snapshots",
  supportDisputes: "marketplace_support_dispute_capability_snapshots",
  analyticsProjections: "marketplace_analytics_projection_capability_snapshots",
  administrationRecords: "marketplace_administration_capability_snapshots",
});
