export { AnalyticsModule } from "./api";
export type { IAnalyticsStore } from "./contracts";
export type {
  GetSalesMetricsDto,
  GetOrderMetricsDto,
  GetCustomerMetricsDto,
  GetSellerMetricsDto,
  GetProductMetricsDto,
  GetMarketplaceMetricsDto,
  RebuildProjectionDto,
} from "./dto";
export {
  type MetricsUpdatedEvent,
  type ProjectionRebuiltEvent,
  createMetricsUpdatedEvent,
  createProjectionRebuiltEvent,
} from "./events";
export {
  type SalesMetrics,
  createEmptySalesMetrics,
  withSalesMetricsUpdate,
  type OrderMetrics,
  createEmptyOrderMetrics,
  withOrderCreatedMetrics,
  withOrderStatusMetrics,
  type CustomerMetrics,
  createEmptyCustomerMetrics,
  withCustomerRegisteredMetrics,
  type SellerMetrics,
  createEmptySellerMetrics,
  withSellerRegisteredMetrics,
  withSellerApprovedMetrics,
  withSellerSuspendedMetrics,
  type ProductMetrics,
  createEmptyProductMetrics,
  withProductCreatedMetrics,
  withProductReadyMetrics,
  type MarketplaceMetrics,
  createEmptyMarketplaceMetrics,
  withListingSubmittedMetrics,
  withListingPublishedMetrics,
  withListingUnpublishedMetrics,
} from "./models";
export {
  type SalesProjection,
  createSalesProjection,
  withSalesProjectionEvent,
  type OrdersProjection,
  createOrdersProjection,
  withOrdersProjectionEvent,
  type CustomersProjection,
  createCustomersProjection,
  withCustomersProjectionEvent,
  type SellersProjection,
  createSellersProjection,
  withSellersProjectionEvent,
  type ProductsProjection,
  createProductsProjection,
  withProductsProjectionEvent,
  type MarketplaceProjection,
  createMarketplaceProjection,
  withMarketplaceProjectionEvent,
} from "./projections";
export {
  AnalyticsService,
  AnalyticsEventSubscriber,
  AnalyticsCapabilityEventName,
  ANALYTICS_CAPABILITY_EVENT_NAMES,
} from "./services";
