/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as BootstrapRouteImport } from './routes/bootstrap'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProfileAddressesRouteImport } from './routes/profile/addresses'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as OrdersIdRouteImport } from './routes/orders/$id'
import { Route as WarehouseOrdersIndexRouteImport } from './routes/warehouse/orders/index'
import { Route as SellerProfileIndexRouteImport } from './routes/seller/profile/index'
import { Route as SellerProductsIndexRouteImport } from './routes/seller/products/index'
import { Route as CourierOrdersIndexRouteImport } from './routes/courier/orders/index'
import { Route as AdminWarehouseIndexRouteImport } from './routes/admin/warehouse/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminSuppliersIndexRouteImport } from './routes/admin/suppliers/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminSellersIndexRouteImport } from './routes/admin/sellers/index'
import { Route as AdminSecurityIndexRouteImport } from './routes/admin/security/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminMarketingIndexRouteImport } from './routes/admin/marketing/index'
import { Route as AdminLogsIndexRouteImport } from './routes/admin/logs/index'
import { Route as AdminIntegrationsIndexRouteImport } from './routes/admin/integrations/index'
import { Route as AdminFinanceIndexRouteImport } from './routes/admin/finance/index'
import { Route as AdminDesignIndexRouteImport } from './routes/admin/design/index'
import { Route as AdminDeliveryIndexRouteImport } from './routes/admin/delivery/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as AdminCouriersIndexRouteImport } from './routes/admin/couriers/index'
import { Route as AdminCatalogIndexRouteImport } from './routes/admin/catalog/index'
import { Route as AdminAutomationIndexRouteImport } from './routes/admin/automation/index'
import { Route as AdminAnalyticsIndexRouteImport } from './routes/admin/analytics/index'
import { Route as AdminAiIndexRouteImport } from './routes/admin/ai/index'
import { Route as WarehouseOrdersIdRouteImport } from './routes/warehouse/orders/$id'
import { Route as SellerProductsIdRouteImport } from './routes/seller/products/$id'
import { Route as CourierOrdersIdRouteImport } from './routes/courier/orders/$id'
import { Route as AdminOrdersIdRouteImport } from './routes/admin/orders/$id'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const BootstrapRoute = BootstrapRouteImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAddressesRoute = ProfileAddressesRouteImport.update({
  id: '/profile/addresses',
  path: '/profile/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseOrdersIndexRoute = WarehouseOrdersIndexRouteImport.update({
  id: '/warehouse/orders/',
  path: '/warehouse/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerProfileIndexRoute = SellerProfileIndexRouteImport.update({
  id: '/seller/profile/',
  path: '/seller/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerProductsIndexRoute = SellerProductsIndexRouteImport.update({
  id: '/seller/products/',
  path: '/seller/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourierOrdersIndexRoute = CourierOrdersIndexRouteImport.update({
  id: '/courier/orders/',
  path: '/courier/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWarehouseIndexRoute = AdminWarehouseIndexRouteImport.update({
  id: '/admin/warehouse/',
  path: '/admin/warehouse/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSuppliersIndexRoute = AdminSuppliersIndexRouteImport.update({
  id: '/admin/suppliers/',
  path: '/admin/suppliers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/admin/settings/',
  path: '/admin/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSellersIndexRoute = AdminSellersIndexRouteImport.update({
  id: '/admin/sellers/',
  path: '/admin/sellers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSecurityIndexRoute = AdminSecurityIndexRouteImport.update({
  id: '/admin/security/',
  path: '/admin/security/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/admin/orders/',
  path: '/admin/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMarketingIndexRoute = AdminMarketingIndexRouteImport.update({
  id: '/admin/marketing/',
  path: '/admin/marketing/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsIndexRoute = AdminLogsIndexRouteImport.update({
  id: '/admin/logs/',
  path: '/admin/logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntegrationsIndexRoute = AdminIntegrationsIndexRouteImport.update({
  id: '/admin/integrations/',
  path: '/admin/integrations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceIndexRoute = AdminFinanceIndexRouteImport.update({
  id: '/admin/finance/',
  path: '/admin/finance/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDesignIndexRoute = AdminDesignIndexRouteImport.update({
  id: '/admin/design/',
  path: '/admin/design/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDeliveryIndexRoute = AdminDeliveryIndexRouteImport.update({
  id: '/admin/delivery/',
  path: '/admin/delivery/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/admin/dashboard/',
  path: '/admin/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCouriersIndexRoute = AdminCouriersIndexRouteImport.update({
  id: '/admin/couriers/',
  path: '/admin/couriers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogIndexRoute = AdminCatalogIndexRouteImport.update({
  id: '/admin/catalog/',
  path: '/admin/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAutomationIndexRoute = AdminAutomationIndexRouteImport.update({
  id: '/admin/automation/',
  path: '/admin/automation/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsIndexRoute = AdminAnalyticsIndexRouteImport.update({
  id: '/admin/analytics/',
  path: '/admin/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiIndexRoute = AdminAiIndexRouteImport.update({
  id: '/admin/ai/',
  path: '/admin/ai/',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseOrdersIdRoute = WarehouseOrdersIdRouteImport.update({
  id: '/warehouse/orders/$id',
  path: '/warehouse/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerProductsIdRoute = SellerProductsIdRouteImport.update({
  id: '/seller/products/$id',
  path: '/seller/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CourierOrdersIdRoute = CourierOrdersIdRouteImport.update({
  id: '/courier/orders/$id',
  path: '/courier/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/admin/orders/$id',
  path: '/admin/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bootstrap': typeof BootstrapRoute
  '/order-success': typeof OrderSuccessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workspace': typeof WorkspaceRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$handle': typeof ProductHandleRoute
  '/profile/addresses': typeof ProfileAddressesRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/courier/orders/$id': typeof CourierOrdersIdRoute
  '/seller/products/$id': typeof SellerProductsIdRoute
  '/warehouse/orders/$id': typeof WarehouseOrdersIdRoute
  '/admin/ai/': typeof AdminAiIndexRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/automation/': typeof AdminAutomationIndexRoute
  '/admin/catalog/': typeof AdminCatalogIndexRoute
  '/admin/couriers/': typeof AdminCouriersIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/delivery/': typeof AdminDeliveryIndexRoute
  '/admin/design/': typeof AdminDesignIndexRoute
  '/admin/finance/': typeof AdminFinanceIndexRoute
  '/admin/integrations/': typeof AdminIntegrationsIndexRoute
  '/admin/logs/': typeof AdminLogsIndexRoute
  '/admin/marketing/': typeof AdminMarketingIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/security/': typeof AdminSecurityIndexRoute
  '/admin/sellers/': typeof AdminSellersIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/suppliers/': typeof AdminSuppliersIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/warehouse/': typeof AdminWarehouseIndexRoute
  '/courier/orders/': typeof CourierOrdersIndexRoute
  '/seller/products/': typeof SellerProductsIndexRoute
  '/seller/profile/': typeof SellerProfileIndexRoute
  '/warehouse/orders/': typeof WarehouseOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bootstrap': typeof BootstrapRoute
  '/order-success': typeof OrderSuccessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workspace': typeof WorkspaceRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$handle': typeof ProductHandleRoute
  '/profile/addresses': typeof ProfileAddressesRoute
  '/admin': typeof AdminIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/courier/orders/$id': typeof CourierOrdersIdRoute
  '/seller/products/$id': typeof SellerProductsIdRoute
  '/warehouse/orders/$id': typeof WarehouseOrdersIdRoute
  '/admin/ai': typeof AdminAiIndexRoute
  '/admin/analytics': typeof AdminAnalyticsIndexRoute
  '/admin/automation': typeof AdminAutomationIndexRoute
  '/admin/catalog': typeof AdminCatalogIndexRoute
  '/admin/couriers': typeof AdminCouriersIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/delivery': typeof AdminDeliveryIndexRoute
  '/admin/design': typeof AdminDesignIndexRoute
  '/admin/finance': typeof AdminFinanceIndexRoute
  '/admin/integrations': typeof AdminIntegrationsIndexRoute
  '/admin/logs': typeof AdminLogsIndexRoute
  '/admin/marketing': typeof AdminMarketingIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/security': typeof AdminSecurityIndexRoute
  '/admin/sellers': typeof AdminSellersIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/suppliers': typeof AdminSuppliersIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/warehouse': typeof AdminWarehouseIndexRoute
  '/courier/orders': typeof CourierOrdersIndexRoute
  '/seller/products': typeof SellerProductsIndexRoute
  '/seller/profile': typeof SellerProfileIndexRoute
  '/warehouse/orders': typeof WarehouseOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bootstrap': typeof BootstrapRoute
  '/order-success': typeof OrderSuccessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workspace': typeof WorkspaceRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$handle': typeof ProductHandleRoute
  '/profile/addresses': typeof ProfileAddressesRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/courier/orders/$id': typeof CourierOrdersIdRoute
  '/seller/products/$id': typeof SellerProductsIdRoute
  '/warehouse/orders/$id': typeof WarehouseOrdersIdRoute
  '/admin/ai/': typeof AdminAiIndexRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/automation/': typeof AdminAutomationIndexRoute
  '/admin/catalog/': typeof AdminCatalogIndexRoute
  '/admin/couriers/': typeof AdminCouriersIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/delivery/': typeof AdminDeliveryIndexRoute
  '/admin/design/': typeof AdminDesignIndexRoute
  '/admin/finance/': typeof AdminFinanceIndexRoute
  '/admin/integrations/': typeof AdminIntegrationsIndexRoute
  '/admin/logs/': typeof AdminLogsIndexRoute
  '/admin/marketing/': typeof AdminMarketingIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/security/': typeof AdminSecurityIndexRoute
  '/admin/sellers/': typeof AdminSellersIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/suppliers/': typeof AdminSuppliersIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/warehouse/': typeof AdminWarehouseIndexRoute
  '/courier/orders/': typeof CourierOrdersIndexRoute
  '/seller/products/': typeof SellerProductsIndexRoute
  '/seller/profile/': typeof SellerProfileIndexRoute
  '/warehouse/orders/': typeof WarehouseOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bootstrap'
    | '/order-success'
    | '/sitemap.xml'
    | '/workspace'
    | '/orders/$id'
    | '/product/$handle'
    | '/profile/addresses'
    | '/admin/'
    | '/orders/'
    | '/admin/orders/$id'
    | '/courier/orders/$id'
    | '/seller/products/$id'
    | '/warehouse/orders/$id'
    | '/admin/ai/'
    | '/admin/analytics/'
    | '/admin/automation/'
    | '/admin/catalog/'
    | '/admin/couriers/'
    | '/admin/dashboard/'
    | '/admin/delivery/'
    | '/admin/design/'
    | '/admin/finance/'
    | '/admin/integrations/'
    | '/admin/logs/'
    | '/admin/marketing/'
    | '/admin/orders/'
    | '/admin/security/'
    | '/admin/sellers/'
    | '/admin/settings/'
    | '/admin/suppliers/'
    | '/admin/users/'
    | '/admin/warehouse/'
    | '/courier/orders/'
    | '/seller/products/'
    | '/seller/profile/'
    | '/warehouse/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bootstrap'
    | '/order-success'
    | '/sitemap.xml'
    | '/workspace'
    | '/orders/$id'
    | '/product/$handle'
    | '/profile/addresses'
    | '/admin'
    | '/orders'
    | '/admin/orders/$id'
    | '/courier/orders/$id'
    | '/seller/products/$id'
    | '/warehouse/orders/$id'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/automation'
    | '/admin/catalog'
    | '/admin/couriers'
    | '/admin/dashboard'
    | '/admin/delivery'
    | '/admin/design'
    | '/admin/finance'
    | '/admin/integrations'
    | '/admin/logs'
    | '/admin/marketing'
    | '/admin/orders'
    | '/admin/security'
    | '/admin/sellers'
    | '/admin/settings'
    | '/admin/suppliers'
    | '/admin/users'
    | '/admin/warehouse'
    | '/courier/orders'
    | '/seller/products'
    | '/seller/profile'
    | '/warehouse/orders'
  id:
    | '__root__'
    | '/'
    | '/bootstrap'
    | '/order-success'
    | '/sitemap.xml'
    | '/workspace'
    | '/orders/$id'
    | '/product/$handle'
    | '/profile/addresses'
    | '/admin/'
    | '/orders/'
    | '/admin/orders/$id'
    | '/courier/orders/$id'
    | '/seller/products/$id'
    | '/warehouse/orders/$id'
    | '/admin/ai/'
    | '/admin/analytics/'
    | '/admin/automation/'
    | '/admin/catalog/'
    | '/admin/couriers/'
    | '/admin/dashboard/'
    | '/admin/delivery/'
    | '/admin/design/'
    | '/admin/finance/'
    | '/admin/integrations/'
    | '/admin/logs/'
    | '/admin/marketing/'
    | '/admin/orders/'
    | '/admin/security/'
    | '/admin/sellers/'
    | '/admin/settings/'
    | '/admin/suppliers/'
    | '/admin/users/'
    | '/admin/warehouse/'
    | '/courier/orders/'
    | '/seller/products/'
    | '/seller/profile/'
    | '/warehouse/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BootstrapRoute: typeof BootstrapRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorkspaceRoute: typeof WorkspaceRoute
  OrdersIdRoute: typeof OrdersIdRoute
  ProductHandleRoute: typeof ProductHandleRoute
  ProfileAddressesRoute: typeof ProfileAddressesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  CourierOrdersIdRoute: typeof CourierOrdersIdRoute
  SellerProductsIdRoute: typeof SellerProductsIdRoute
  WarehouseOrdersIdRoute: typeof WarehouseOrdersIdRoute
  AdminAiIndexRoute: typeof AdminAiIndexRoute
  AdminAnalyticsIndexRoute: typeof AdminAnalyticsIndexRoute
  AdminAutomationIndexRoute: typeof AdminAutomationIndexRoute
  AdminCatalogIndexRoute: typeof AdminCatalogIndexRoute
  AdminCouriersIndexRoute: typeof AdminCouriersIndexRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminDeliveryIndexRoute: typeof AdminDeliveryIndexRoute
  AdminDesignIndexRoute: typeof AdminDesignIndexRoute
  AdminFinanceIndexRoute: typeof AdminFinanceIndexRoute
  AdminIntegrationsIndexRoute: typeof AdminIntegrationsIndexRoute
  AdminLogsIndexRoute: typeof AdminLogsIndexRoute
  AdminMarketingIndexRoute: typeof AdminMarketingIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminSecurityIndexRoute: typeof AdminSecurityIndexRoute
  AdminSellersIndexRoute: typeof AdminSellersIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminSuppliersIndexRoute: typeof AdminSuppliersIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminWarehouseIndexRoute: typeof AdminWarehouseIndexRoute
  CourierOrdersIndexRoute: typeof CourierOrdersIndexRoute
  SellerProductsIndexRoute: typeof SellerProductsIndexRoute
  SellerProfileIndexRoute: typeof SellerProfileIndexRoute
  WarehouseOrdersIndexRoute: typeof WarehouseOrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bootstrap': {
      id: '/bootstrap'
      path: '/bootstrap'
      fullPath: '/bootstrap'
      preLoaderRoute: typeof BootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/addresses': {
      id: '/profile/addresses'
      path: '/profile/addresses'
      fullPath: '/profile/addresses'
      preLoaderRoute: typeof ProfileAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/orders/': {
      id: '/warehouse/orders/'
      path: '/warehouse/orders'
      fullPath: '/warehouse/orders/'
      preLoaderRoute: typeof WarehouseOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/profile/': {
      id: '/seller/profile/'
      path: '/seller/profile'
      fullPath: '/seller/profile/'
      preLoaderRoute: typeof SellerProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/products/': {
      id: '/seller/products/'
      path: '/seller/products'
      fullPath: '/seller/products/'
      preLoaderRoute: typeof SellerProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courier/orders/': {
      id: '/courier/orders/'
      path: '/courier/orders'
      fullPath: '/courier/orders/'
      preLoaderRoute: typeof CourierOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/warehouse/': {
      id: '/admin/warehouse/'
      path: '/admin/warehouse'
      fullPath: '/admin/warehouse/'
      preLoaderRoute: typeof AdminWarehouseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/suppliers/': {
      id: '/admin/suppliers/'
      path: '/admin/suppliers'
      fullPath: '/admin/suppliers/'
      preLoaderRoute: typeof AdminSuppliersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/admin/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sellers/': {
      id: '/admin/sellers/'
      path: '/admin/sellers'
      fullPath: '/admin/sellers/'
      preLoaderRoute: typeof AdminSellersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/security/': {
      id: '/admin/security/'
      path: '/admin/security'
      fullPath: '/admin/security/'
      preLoaderRoute: typeof AdminSecurityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/admin/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/marketing/': {
      id: '/admin/marketing/'
      path: '/admin/marketing'
      fullPath: '/admin/marketing/'
      preLoaderRoute: typeof AdminMarketingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logs/': {
      id: '/admin/logs/'
      path: '/admin/logs'
      fullPath: '/admin/logs/'
      preLoaderRoute: typeof AdminLogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/integrations/': {
      id: '/admin/integrations/'
      path: '/admin/integrations'
      fullPath: '/admin/integrations/'
      preLoaderRoute: typeof AdminIntegrationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/finance/': {
      id: '/admin/finance/'
      path: '/admin/finance'
      fullPath: '/admin/finance/'
      preLoaderRoute: typeof AdminFinanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/design/': {
      id: '/admin/design/'
      path: '/admin/design'
      fullPath: '/admin/design/'
      preLoaderRoute: typeof AdminDesignIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/delivery/': {
      id: '/admin/delivery/'
      path: '/admin/delivery'
      fullPath: '/admin/delivery/'
      preLoaderRoute: typeof AdminDeliveryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/couriers/': {
      id: '/admin/couriers/'
      path: '/admin/couriers'
      fullPath: '/admin/couriers/'
      preLoaderRoute: typeof AdminCouriersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalog/': {
      id: '/admin/catalog/'
      path: '/admin/catalog'
      fullPath: '/admin/catalog/'
      preLoaderRoute: typeof AdminCatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/automation/': {
      id: '/admin/automation/'
      path: '/admin/automation'
      fullPath: '/admin/automation/'
      preLoaderRoute: typeof AdminAutomationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics/': {
      id: '/admin/analytics/'
      path: '/admin/analytics'
      fullPath: '/admin/analytics/'
      preLoaderRoute: typeof AdminAnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai/': {
      id: '/admin/ai/'
      path: '/admin/ai'
      fullPath: '/admin/ai/'
      preLoaderRoute: typeof AdminAiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/orders/$id': {
      id: '/warehouse/orders/$id'
      path: '/warehouse/orders/$id'
      fullPath: '/warehouse/orders/$id'
      preLoaderRoute: typeof WarehouseOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/products/$id': {
      id: '/seller/products/$id'
      path: '/seller/products/$id'
      fullPath: '/seller/products/$id'
      preLoaderRoute: typeof SellerProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courier/orders/$id': {
      id: '/courier/orders/$id'
      path: '/courier/orders/$id'
      fullPath: '/courier/orders/$id'
      preLoaderRoute: typeof CourierOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/admin/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BootstrapRoute: BootstrapRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorkspaceRoute: WorkspaceRoute,
  OrdersIdRoute: OrdersIdRoute,
  ProductHandleRoute: ProductHandleRoute,
  ProfileAddressesRoute: ProfileAddressesRoute,
  AdminIndexRoute: AdminIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  CourierOrdersIdRoute: CourierOrdersIdRoute,
  SellerProductsIdRoute: SellerProductsIdRoute,
  WarehouseOrdersIdRoute: WarehouseOrdersIdRoute,
  AdminAiIndexRoute: AdminAiIndexRoute,
  AdminAnalyticsIndexRoute: AdminAnalyticsIndexRoute,
  AdminAutomationIndexRoute: AdminAutomationIndexRoute,
  AdminCatalogIndexRoute: AdminCatalogIndexRoute,
  AdminCouriersIndexRoute: AdminCouriersIndexRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminDeliveryIndexRoute: AdminDeliveryIndexRoute,
  AdminDesignIndexRoute: AdminDesignIndexRoute,
  AdminFinanceIndexRoute: AdminFinanceIndexRoute,
  AdminIntegrationsIndexRoute: AdminIntegrationsIndexRoute,
  AdminLogsIndexRoute: AdminLogsIndexRoute,
  AdminMarketingIndexRoute: AdminMarketingIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminSecurityIndexRoute: AdminSecurityIndexRoute,
  AdminSellersIndexRoute: AdminSellersIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminSuppliersIndexRoute: AdminSuppliersIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminWarehouseIndexRoute: AdminWarehouseIndexRoute,
  CourierOrdersIndexRoute: CourierOrdersIndexRoute,
  SellerProductsIndexRoute: SellerProductsIndexRoute,
  SellerProfileIndexRoute: SellerProfileIndexRoute,
  WarehouseOrdersIndexRoute: WarehouseOrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
