/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProfileAddressesRouteImport } from './routes/profile/addresses'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as OrdersIdRouteImport } from './routes/orders/$id'
import { Route as WarehouseOrdersIndexRouteImport } from './routes/warehouse/orders/index'
import { Route as SellerProductsIndexRouteImport } from './routes/seller/products/index'
import { Route as CourierOrdersIndexRouteImport } from './routes/courier/orders/index'
import { Route as AdminWarehouseIndexRouteImport } from './routes/admin/warehouse/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as AdminCatalogIndexRouteImport } from './routes/admin/catalog/index'
import { Route as WarehouseOrdersIdRouteImport } from './routes/warehouse/orders/$id'
import { Route as SellerProductsIdRouteImport } from './routes/seller/products/$id'
import { Route as CourierOrdersIdRouteImport } from './routes/courier/orders/$id'
import { Route as AdminOrdersIdRouteImport } from './routes/admin/orders/$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAddressesRoute = ProfileAddressesRouteImport.update({
  id: '/profile/addresses',
  path: '/profile/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseOrdersIndexRoute = WarehouseOrdersIndexRouteImport.update({
  id: '/warehouse/orders/',
  path: '/warehouse/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerProductsIndexRoute = SellerProductsIndexRouteImport.update({
  id: '/seller/products/',
  path: '/seller/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourierOrdersIndexRoute = CourierOrdersIndexRouteImport.update({
  id: '/courier/orders/',
  path: '/courier/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWarehouseIndexRoute = AdminWarehouseIndexRouteImport.update({
  id: '/admin/warehouse/',
  path: '/admin/warehouse/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/admin/settings/',
  path: '/admin/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/admin/orders/',
  path: '/admin/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/admin/dashboard/',
  path: '/admin/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogIndexRoute = AdminCatalogIndexRouteImport.update({
  id: '/admin/catalog/',
  path: '/admin/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseOrdersIdRoute = WarehouseOrdersIdRouteImport.update({
  id: '/warehouse/orders/$id',
  path: '/warehouse/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerProductsIdRoute = SellerProductsIdRouteImport.update({
  id: '/seller/products/$id',
  path: '/seller/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CourierOrdersIdRoute = CourierOrdersIdRouteImport.update({
  id: '/courier/orders/$id',
  path: '/courier/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/admin/orders/$id',
  path: '/admin/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/order-success': typeof OrderSuccessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$handle': typeof ProductHandleRoute
  '/profile/addresses': typeof ProfileAddressesRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/courier/orders/$id': typeof CourierOrdersIdRoute
  '/seller/products/$id': typeof SellerProductsIdRoute
  '/warehouse/orders/$id': typeof WarehouseOrdersIdRoute
  '/admin/catalog/': typeof AdminCatalogIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/warehouse/': typeof AdminWarehouseIndexRoute
  '/courier/orders/': typeof CourierOrdersIndexRoute
  '/seller/products/': typeof SellerProductsIndexRoute
  '/warehouse/orders/': typeof WarehouseOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/order-success': typeof OrderSuccessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$handle': typeof ProductHandleRoute
  '/profile/addresses': typeof ProfileAddressesRoute
  '/admin': typeof AdminIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/courier/orders/$id': typeof CourierOrdersIdRoute
  '/seller/products/$id': typeof SellerProductsIdRoute
  '/warehouse/orders/$id': typeof WarehouseOrdersIdRoute
  '/admin/catalog': typeof AdminCatalogIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/warehouse': typeof AdminWarehouseIndexRoute
  '/courier/orders': typeof CourierOrdersIndexRoute
  '/seller/products': typeof SellerProductsIndexRoute
  '/warehouse/orders': typeof WarehouseOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/order-success': typeof OrderSuccessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$handle': typeof ProductHandleRoute
  '/profile/addresses': typeof ProfileAddressesRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/courier/orders/$id': typeof CourierOrdersIdRoute
  '/seller/products/$id': typeof SellerProductsIdRoute
  '/warehouse/orders/$id': typeof WarehouseOrdersIdRoute
  '/admin/catalog/': typeof AdminCatalogIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/warehouse/': typeof AdminWarehouseIndexRoute
  '/courier/orders/': typeof CourierOrdersIndexRoute
  '/seller/products/': typeof SellerProductsIndexRoute
  '/warehouse/orders/': typeof WarehouseOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/order-success'
    | '/sitemap.xml'
    | '/orders/$id'
    | '/product/$handle'
    | '/profile/addresses'
    | '/admin/'
    | '/orders/'
    | '/admin/orders/$id'
    | '/courier/orders/$id'
    | '/seller/products/$id'
    | '/warehouse/orders/$id'
    | '/admin/catalog/'
    | '/admin/dashboard/'
    | '/admin/orders/'
    | '/admin/settings/'
    | '/admin/warehouse/'
    | '/courier/orders/'
    | '/seller/products/'
    | '/warehouse/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/order-success'
    | '/sitemap.xml'
    | '/orders/$id'
    | '/product/$handle'
    | '/profile/addresses'
    | '/admin'
    | '/orders'
    | '/admin/orders/$id'
    | '/courier/orders/$id'
    | '/seller/products/$id'
    | '/warehouse/orders/$id'
    | '/admin/catalog'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/settings'
    | '/admin/warehouse'
    | '/courier/orders'
    | '/seller/products'
    | '/warehouse/orders'
  id:
    | '__root__'
    | '/'
    | '/order-success'
    | '/sitemap.xml'
    | '/orders/$id'
    | '/product/$handle'
    | '/profile/addresses'
    | '/admin/'
    | '/orders/'
    | '/admin/orders/$id'
    | '/courier/orders/$id'
    | '/seller/products/$id'
    | '/warehouse/orders/$id'
    | '/admin/catalog/'
    | '/admin/dashboard/'
    | '/admin/orders/'
    | '/admin/settings/'
    | '/admin/warehouse/'
    | '/courier/orders/'
    | '/seller/products/'
    | '/warehouse/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  OrdersIdRoute: typeof OrdersIdRoute
  ProductHandleRoute: typeof ProductHandleRoute
  ProfileAddressesRoute: typeof ProfileAddressesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  CourierOrdersIdRoute: typeof CourierOrdersIdRoute
  SellerProductsIdRoute: typeof SellerProductsIdRoute
  WarehouseOrdersIdRoute: typeof WarehouseOrdersIdRoute
  AdminCatalogIndexRoute: typeof AdminCatalogIndexRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminWarehouseIndexRoute: typeof AdminWarehouseIndexRoute
  CourierOrdersIndexRoute: typeof CourierOrdersIndexRoute
  SellerProductsIndexRoute: typeof SellerProductsIndexRoute
  WarehouseOrdersIndexRoute: typeof WarehouseOrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/addresses': {
      id: '/profile/addresses'
      path: '/profile/addresses'
      fullPath: '/profile/addresses'
      preLoaderRoute: typeof ProfileAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/orders/': {
      id: '/warehouse/orders/'
      path: '/warehouse/orders'
      fullPath: '/warehouse/orders/'
      preLoaderRoute: typeof WarehouseOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/products/': {
      id: '/seller/products/'
      path: '/seller/products'
      fullPath: '/seller/products/'
      preLoaderRoute: typeof SellerProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courier/orders/': {
      id: '/courier/orders/'
      path: '/courier/orders'
      fullPath: '/courier/orders/'
      preLoaderRoute: typeof CourierOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/warehouse/': {
      id: '/admin/warehouse/'
      path: '/admin/warehouse'
      fullPath: '/admin/warehouse/'
      preLoaderRoute: typeof AdminWarehouseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/admin/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/admin/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalog/': {
      id: '/admin/catalog/'
      path: '/admin/catalog'
      fullPath: '/admin/catalog/'
      preLoaderRoute: typeof AdminCatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/orders/$id': {
      id: '/warehouse/orders/$id'
      path: '/warehouse/orders/$id'
      fullPath: '/warehouse/orders/$id'
      preLoaderRoute: typeof WarehouseOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/products/$id': {
      id: '/seller/products/$id'
      path: '/seller/products/$id'
      fullPath: '/seller/products/$id'
      preLoaderRoute: typeof SellerProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courier/orders/$id': {
      id: '/courier/orders/$id'
      path: '/courier/orders/$id'
      fullPath: '/courier/orders/$id'
      preLoaderRoute: typeof CourierOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/admin/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  OrdersIdRoute: OrdersIdRoute,
  ProductHandleRoute: ProductHandleRoute,
  ProfileAddressesRoute: ProfileAddressesRoute,
  AdminIndexRoute: AdminIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  CourierOrdersIdRoute: CourierOrdersIdRoute,
  SellerProductsIdRoute: SellerProductsIdRoute,
  WarehouseOrdersIdRoute: WarehouseOrdersIdRoute,
  AdminCatalogIndexRoute: AdminCatalogIndexRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminWarehouseIndexRoute: AdminWarehouseIndexRoute,
  CourierOrdersIndexRoute: CourierOrdersIndexRoute,
  SellerProductsIndexRoute: SellerProductsIndexRoute,
  WarehouseOrdersIndexRoute: WarehouseOrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
