-- Задача №231 — sort_order must round-trip arbitrarily long decimal values
-- (e.g. 1.15555555555) with zero precision loss, end to end, including over
-- the wire. products.sort_order stays `numeric` with no precision/scale
-- (added in Задача №230) — that part already supports unbounded fractions
-- and is required for correct SQL comparison/MAX(). The remaining risk is
-- supabase-js/postgrest-js: every HTTP response is parsed with the
-- platform's native JSON.parse *inside the library*, before any of our own
-- code runs — a JSON *number* literal becomes a lossy IEEE-754 double at
-- that point, and no amount of String()/Number() afterwards can undo it.
--
-- Fix: PostgREST serializes a `text` column as a JSON *string*, which
-- JSON.parse always preserves verbatim (no numeric parsing). This generated
-- column mirrors sort_order as text purely so every read for display/
-- editing goes through it instead of the raw numeric column. It's
-- read-only (Postgres maintains it) — writes still target sort_order
-- directly, where Postgres's own text-to-numeric input parser (not any JS
-- float path) interprets the decimal string sent from the form, so full
-- precision survives that direction too.
ALTER TABLE public.products
  ADD COLUMN sort_order_text text GENERATED ALWAYS AS (sort_order::text) STORED;

COMMENT ON COLUMN public.products.sort_order_text IS
  'Read-only text mirror of sort_order (numeric), generated by Postgres so PostgREST serializes it as a JSON string rather than a JSON number — avoids precision loss in supabase-js''s JSON.parse for arbitrarily long decimals. Never write to this column directly; write sort_order instead.';

-- Atomic "current max + 1" for auto-assigning a new product's sort_order on
-- creation when the admin leaves the field empty. Computed entirely in
-- Postgres numeric arithmetic (unbounded precision, real decimal
-- comparison via SQL MAX — not a JS Math.max over possibly-imprecise
-- parsed numbers) and cast to text before it ever leaves the database, for
-- the same JSON-number-vs-string reason as sort_order_text above.
CREATE OR REPLACE FUNCTION public.next_product_sort_order()
RETURNS text
LANGUAGE sql
STABLE
AS $$
  SELECT (COALESCE(MAX(sort_order), 0) + 1)::text FROM public.products;
$$;

GRANT EXECUTE ON FUNCTION public.next_product_sort_order() TO service_role;
