-- Задача №232 — same precision-safe pattern just built for products
-- (Задача №230/231), applied to categories.sort_order — but scoped PER
-- PARENT (variant Б), not a single global list like products: categories
-- and subcategories share one table (parent_id IS NULL vs NOT NULL), and
-- a subcategory's position only needs to be meaningful among its own
-- siblings (same parent_id) — two subcategories of different parents
-- sharing the same number is normal and expected, not a conflict.

-- INT -> NUMERIC (no precision/scale, same as products) so a subcategory
-- can be inserted between two existing ones (e.g. 1.1 between 1 and 2)
-- without renumbering its siblings. This column is shared by top-level
-- categories (parent_id IS NULL) too — the type change applies to every
-- row (unavoidable, one column), but existing values are preserved exactly
-- (INT -> NUMERIC never loses precision) and top-level ordering/behavior
-- is otherwise untouched by this migration.
ALTER TABLE public.categories
  ALTER COLUMN sort_order TYPE NUMERIC USING sort_order::numeric,
  ALTER COLUMN sort_order SET DEFAULT 0;

-- Same JSON.parse-precision-loss workaround as products.sort_order_text:
-- PostgREST serializes a `text` column as a JSON string (preserved
-- verbatim by supabase-js's JSON.parse), whereas the raw `numeric` column
-- would be serialized as a JSON number and silently rounded to a lossy
-- IEEE-754 double by the same JSON.parse, before any of our code runs.
-- Every read for display/editing goes through this column now.
ALTER TABLE public.categories
  ADD COLUMN sort_order_text text GENERATED ALWAYS AS (sort_order::text) STORED;

COMMENT ON COLUMN public.categories.sort_order_text IS
  'Read-only text mirror of sort_order (numeric), generated by Postgres so PostgREST serializes it as a JSON string rather than a JSON number — avoids precision loss in supabase-js''s JSON.parse for long decimals. Never write to this column directly; write sort_order instead.';

-- Current-max+1 for auto-assigning a new category/subcategory's sort_order
-- on creation when left empty — scoped to siblings of the SAME parent_id
-- (NULL-safe: p_parent_id => NULL correctly matches only top-level
-- categories via IS NOT DISTINCT FROM, reproducing the exact same scoping
-- the admin repository's pre-existing nextSortOrder() JS helper already
-- used — this function replaces that helper's raw-numeric SELECT+JS-math
-- with a real SQL MAX() cast to text, for the same precision reason as
-- sort_order_text). Named for its primary exposed use (the subcategory
-- form field this task adds), but the underlying scoping is general and
-- also serves top-level category creation, unchanged from today's
-- behavior.
CREATE OR REPLACE FUNCTION public.next_subcategory_sort_order(p_parent_id uuid)
RETURNS text
LANGUAGE sql
STABLE
AS $$
  SELECT (COALESCE(MAX(sort_order), 0) + 1)::text
  FROM public.categories
  WHERE parent_id IS NOT DISTINCT FROM p_parent_id;
$$;

GRANT EXECUTE ON FUNCTION public.next_subcategory_sort_order(uuid) TO service_role;

-- Backfill: existing subcategories (parent_id IS NOT NULL) had gaps and
-- inconsistent starting offsets (some groups starting at 0, one at 10,
-- with holes from since-deleted siblings) — confirmed live, no actual
-- duplicates within any single parent, just messy numbering, matching
-- Дониар's "переполняются и не получается разложить" complaint.
-- Renumbers each parent's subcategories to clean sequential 1..n,
-- preserving their current relative order (sort_order asc, tie-broken by
-- created_at) so the storefront looks identical right after this runs.
-- Top-level categories (parent_id IS NULL) are NOT touched — out of scope
-- for this task.
WITH ranked AS (
  SELECT id, ROW_NUMBER() OVER (PARTITION BY parent_id ORDER BY sort_order ASC, created_at ASC) AS rn
  FROM public.categories
  WHERE parent_id IS NOT NULL
)
UPDATE public.categories c
SET sort_order = ranked.rn
FROM ranked
WHERE c.id = ranked.id;
